version: "3.9"
services:
  db_inventory:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - "${PORT_DB_DOCKER}:${PORT_DB}"
    volumes:
      - db-inventory-data:/var/lib/postgresql/data

  app_inventory:
    build: .
    ports:
      - ${PORT_DOCKER}:${PORT}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db_inventory
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    depends_on:
      - db_inventory
    volumes:
      - .:/usr/src/app  # Mapea el código fuente local al contenedor
      - /usr/src/app/node_modules  # Evita que se sobreescriban los módulos de node
volumes:
  db-inventory-data:
